const config = {
  AZURE_CHAT_OPEN_AI_API_KEY: process.env.AZURE_CHAT_OPEN_AI_API_KEY,
  AZURE_CHAT_OPEN_AI_RESOURCE_NAME: process.env.AZURE_CHAT_OPEN_AI_RESOURCE_NAME,
  AZURE_CHAT_OPEN_AI_ENDPOINT: process.env.AZURE_CHAT_OPEN_AI_ENDPOINT,
  AZURE_CHAT_OPEN_AI_API_VERSION: process.env.AZURE_CHAT_OPEN_AI_API_VERSION,
  AZURE_CHAT_OPEN_AI_MODEL_NAME: process.env.AZURE_CHAT_OPEN_AI_MODEL_NAME,
};

export default config;
